baseURL = "/gemfire-developer-website"
title = "VMware Gemfire"
publishDir = "public"
contentDir = "content"
canonifyURLs = false
enableRobotsTXT = true
removePathAccents = true

# Continue build even if we hit GitHub API rate limit
# This only affects code sample page READMEs
ignoreErrors = ["error-remote-getjson"]

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

#disableKinds = ["taxonomy", "taxonomyTerm"]

[taxonomies]
featured = "featured"
topicgroup = "topicgroups"
tag = "tags"
team = "team"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
#id = "UA-00000000-0"

# Language settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

[languages]
  [languages.en]
    contentDir = 'content'
    languageName = "English"
    weight = 1
  [languages.kr]
    contentDir = "content/kr"
    languageName = "Korean"
    weight = 2

# Language configuration
#[languages]
#[languages.en]
#title = "Goldydocs"
#description = "A Docsy example site"
#languageName ="English"
# Weight used for sorting.
#weight = 1
#[languages.no]
#title = "Goldydocs"
#description = "Docsy er operativsystem for skyen"
#languageName ="Norsk"
#contentDir = "content/no"
#time_format_default = "02.01.2006"
#time_format_blog = "02.01.2006"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  # Highlighting config
  [markup.highlight]
    codeFences = true
    noClasses = false
#    lineNos = true
#    style = "monokai"
  [markup.tableOfContents]
    endLevel = 2

# Everything below this are Site Params

[params]
# Date and RSS settings
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
# Sections to publish in the main RSS feed.
rss_sections = ["blog","tv-episode"]

workshops_url_prod = "https://workshop-auth.esp.vmware.com/workshop/tanzu_devportal/"
workshops_url_staging = "https://workshop-auth.esp-staging.vmware-aws.com/workshop/tanzu_devportal/"

copyright = "VMware, Inc"
privacy_policy = "https://www.vmware.com/help/privacy.html"
terms_of_use = "https://www.vmware.com/help/legal.html"
california_privacy_rights = "https://www.vmware.com/help/privacy/california-privacy-rights.html"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
# version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
#url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
#github_repo = "https://github.com/google/docsy-example"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
#github_project_repo = "https://github.com/google/docsy"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

#Main Nav Bar Menu Items
[menu]
  [[menu.main]]
    identifier = "install"
    name = "Install"
    weight = 10

  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    weight = 20

  [[menu.main]]
    identifier = "examples"
    name = "Examples"
    Title = 'examples section'
    weight = 25
    url = '/examples/'

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    Title = 'blog section'
    weight = 30
    url = '/blog/'

  [[menu.main]]
    identifier = "download"
    name = "Download"
    weight = 35

#Install Menu Items
  [[menu.main]]
    identifier = "gfinstall"
    name = "GemFire"
    parent = "install"
    weight = 10
    url = "https://docs.vmware.com/en/VMware-GemFire/9.15/gf/getting_started-installation-install_intro.html"

  [[menu.main]]
    identifier = "gf4tasinstall"
    name = "GemFire for TAS"
    parent = "install"
    weight = 20
    url = "https://docs.vmware.com/en/VMware-GemFire-for-Tanzu-Application-Service/1.14/gf-tas/content-operator.html"

  [[menu.main]]
    identifier = "gf4k8sinstall"
    name = "GemFire for Kubernetes"
    parent = "install"
    weight = 30
    url = "https://docs.vmware.com/en/VMware-GemFire-for-Kubernetes/2.1/gf-k8s/supported-configurations.html"


#Documentation Menu Items
  [[menu.main]]
    id = "gfdoc"
    name = "GemFire"
    parent = "documentation"
    weight = 10
    url = "https://docs.vmware.com/en/VMware-GemFire/index.html"
    [menu.main.params]
      topicgroups = "Products"

  [[menu.main]]
    id = "gf4tasdoc"
    name = "GemFire for TAS"
    parent = "documentation"
    weight = 20
    url = "https://docs.vmware.com/en/VMware-GemFire-for-Tanzu-Application-Service/index.html"
    [menu.main.params]
      topicgroups = "Products"

  [[menu.main]]
    id = "gf4k8sdoc"
    name = "GemFire for Kubernetes"
    parent = "documentation"
    weight = 30
    url = "https://docs.vmware.com/en/VMware-GemFire-for-Kubernetes/index.html"
    [menu.main.params]
      topicgroups = "Products"

  [[menu.main]]
    name = "Spring Boot for GemFire"
    parent = "documentation"
    weight = 40
    url = "https://docs.vmware.com/en/Spring-Boot-for-VMware-GemFire/index.html"
    [menu.main.params]
      topicgroups = "Clients"

  [[menu.main]]
    name = "Spring Data for GemFire"
    parent = "documentation"
    weight = 50
    url = "https://docs.vmware.com/en/Spring-Data-for-VMware-GemFire/index.html"
    [menu.main.params]
      topicgroups = "Clients"

  [[menu.main]]
    name = "Native Client"
    parent = "documentation"
    weight = 60
    url = "https://docs.vmware.com/en/Native-Client-for-VMware-GemFire/index.html"
    [menu.main.params]
      topicgroups = "Clients"

  [[menu.main]]
    name = "Node.js for GemFire"
    parent = "documentation"
    weight = 70
    url = "https://docs.vmware.com/en/Node.js-Client-for-VMware-GemFire/2.0/gf-nodeclient/about-client-users-guide.html"
    [menu.main.params]
      topicgroups = "Clients"

  [[menu.main]]
    name = "GemFire for Redis Apps"
    parent = "documentation"
    weight = 80
    url = "https://docs.vmware.com/en/VMware-GemFire-for-Redis-Apps/index.html"
    [menu.main.params]
      topicgroups = "Extensions"


#Download Menu Items
  [[menu.main]]
    identifier = "gfdownload"
    Name = "GemFire"
    parent = "download"
    weight = 10
    url = "https://network.pivotal.io/products/pivotal-gemfire/"
    [menu.main.params]
      topicgroups = "Products"

  [[menu.main]]
    identifier = "gf4tasdownload"
    Name = "GemFire for TAS"
    parent = "download"
    weight = 20
    url = "https://network.pivotal.io/products/tanzu-gemfire-for-vms/"
    [menu.main.params]
      topicgroups = "Products"


  [[menu.main]]
    identifier = "gf4k8sdownload"
    Name = "GemFire for Kubernetes"
    parent = "download"
    weight = 30
    url = "https://network.pivotal.io/products/tanzu-gemfire-for-kubernetes/"
    [menu.main.params]
      topicgroups = "Products"

  [[menu.main]]
    identifier = "nativeclientdl"
    Name = "Native Client"
    parent = "download"
    weight = 40
    url = "https://network.pivotal.io/products/pivotal-gemfire/#/releases/1157686"
    [menu.main.params]
      topicgroups = "Clients"

  [[menu.main]]
    identifier = "nodejsdl"
    Name = "Node.js for Gemfire"
    parent = "download"
    weight = 50
    url = "https://network.pivotal.io/products/pivotal-gemfire/#/releases/765264"
    [menu.main.params]
      topicgroups = "Clients"

  [[menu.main]]
    identifier = "gf4radl"
    Name = "GemFire for Redis Apps"
    parent = "download"
    weight = 60
    url = "https://network.pivotal.io/products/tanzu-gemfire-for-redis-apps/"
    [menu.main.params]
      topicgroups = "Extensions"


# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
#version_menu = "Get Started"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "https://tanzu.vmware.com/newsletter-subscription"
	icon = "fa fa-envelope"
        desc = "Discussion and help from your fellow users"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name ="Twitter"
	url = "https://twitter.com/VMwareTanzu"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter for all the latest news."
[[params.links.developer]]
	name = "YouTube"
	url = "https://www.youtube.com/VMwareTanzu"
	icon = "fab fa-youtube"
    desc = "See demos of modern app technologies in action."
[[params.links.developer]]
	name = "Stack Overflow"
	url = "https://stackoverflow.com/questions/tagged/vmware-tanzu"
	icon = "fab fa-stack-overflow"
        desc = "Ask practical questions and get curated answers."
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/vmware-tanzu"
	icon = "fab fa-github"
        desc = "Explore our open source projects and sample code."
[[params.links.developer]]
	name = "Twitch"
	url = "https://twitch.com/vmwaretanzu"
	icon = "fab fa-twitch"
        desc = "Watch our modern app development live stream."


[frontmatter]
  lastmod = ["lastmod", ":git", "date"]

# See https://github.com/gohugoio/hugo/releases/tag/v0.91.0
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_', '^COMMIT_', '^CONTEXT']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

[outputs]
  home = ["HTML", "RSS", "_Redirects"]

[outputFormats._Redirects]
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true
