

[context.production]
  publish = "public"
  command = "git submodule update -f --init --recursive && npm install && hugo --gc --minify"


[context.production.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"